apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nonml-prophet
  name: nonml-prophet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nonml-prophet
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: nonml-prophet
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'echo Waiting for Kafka...; while ! nc -z kafka 9092; do sleep 1; done; echo Kafka is up!']
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: AWS_S3_ADDRESSING_STYLE
              value: path
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: CONSUMER_GROUP_ID
              value: nonml-prophet
            - name: CONSUMER_TOPIC
              value: training-data
            - name: GATEWAY_URL
              value: http://fastapi-app:8000
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: PRODUCER_TOPIC
              value: model-training
            - name: MODEL_TYPE
              value: PROPHET
            - name: TRAIN_TEST_SPLIT
              value: "0.8"
            - name: OUTPUT_SEQ_LEN
              value: "1"
            - name: FAILURE_MAX_RETRIES
              value: "3"
            - name: N_CHANGEPOINTS
              value: "50"
            - name: CHANGEPOINT_RANGE
              value: "0.8"
            - name: YEARLY_SEASONALITY
              value: auto
            - name: WEEKLY_SEASONALITY
              value: auto
            - name: DAILY_SEASONALITY
              value: auto
            - name: SEASONALITY_MODE
              value: additive
            - name: SEASONALITY_PRIOR_SCALE
              value: "20"
            - name: HOLIDAYS_PRIOR_SCALE
              value: "10"
            - name: CHANGEPOINT_PRIOR_SCALE
              value: "0.1"
            - name: COUNTRY
              value: US
            - name: SKIP_DUPLICATE_CONFIGS
              value: "1"
            - name: DUP_CACHE_MAX
              value: "500"
          image: nonml:latest
          imagePullPolicy: IfNotPresent
          name: nonml-prophet
          ports:
            - containerPort: 8021
              protocol: TCP
      restartPolicy: Always
